/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "7.1.2"
    kotlin("jvm") version "1.9.23"
}

repositories {
    mavenLocal()
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    maven("https://repo.imanity.dev/imanity-libraries/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    maven("https://nexuslite.gcnt.net/repos/gcnt")
    maven("https://repo.codemc.org/repository/maven-public/")
    maven("https://repo.maven.apache.org/maven2/")
    mavenCentral()
}

dependencies {
    api("com.iridium:IridiumColorAPI:1.0.6")
    api("io.github.leonardosnt:bungeechannelapi:1.0.0-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.22")
    compileOnly("org.spigotmc:spigot-api:1.18.1-R0.1-SNAPSHOT")
    compileOnly("dev._2lstudios:Jedis-Wrapper:4.1.1")
    compileOnly("dev._2lstudios:Milkshake-Bukkit:1.3")
    compileOnly("dev._2lstudios:InterfaceMaker:1.0.0")
    compileOnly("me.clip:placeholderapi:2.11.1")
    compileOnly("net.gcnt:skywarsreloaded:5.6.1")
    implementation("com.google.inject:guice:5.0.1")
    compileOnly("org.mcwonderland:KotlinLib:1.9.23b1")
}

group = "dev._2lstudios"
version = "0.1.0"
description = "AdvancedParties"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}