/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.imanity.dev/imanity-libraries/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://nexuslite.gcnt.net/repos/gcnt")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.iridium:IridiumColorAPI:1.0.6")
    api("io.github.leonardosnt:bungeechannelapi:1.0.0-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.22")
    compileOnly("org.spigotmc:spigot-api:1.18.1-R0.1-SNAPSHOT")
    compileOnly("dev._2lstudios:Jedis-Wrapper:4.1.1")
    compileOnly("dev._2lstudios:Milkshake-Bukkit:1.3")
    compileOnly("dev._2lstudios:InterfaceMaker:1.0.0")
    compileOnly("me.clip:placeholderapi:2.11.1")
    compileOnly("net.gcnt:skywarsreloaded:5.6.1")
}

group = "dev._2lstudios"
version = "0.1.0"
description = "AdvancedParties"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
