name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
depend: ["Milkshake-Bukkit", "Jedis", "KotlinLib"]
softdepend: ["PlaceholderAPI", "InterfaceMaker", "Skywars"]
api-version: 1.13
commands:
  advancedparties:
    aliases: ["party", "p"]
    description: "Main parties command"